### ISSUE TITLE
How to auto hide icons?

### ISSUE THREAD

**Issue by wupuyuan** [Mortennn/Dozer#82]
Helllo:
  I like Dozer very much, and I don't know how to hide icons like title.

**Comment by thebitguru** [comment]
@wupuyuan I am a new Dozer user and the two dots approach takes a few minutes to get used to.  It might be helpful to see a screenshot of what you are seeing.  I was able to configure it to my liking and auto hiding is working as expected.

**Comment by wupuyuan** [comment]
@thebitguru thx for your mind, I tried to find and do same thing like video , but it does not work on my mac ...
I think Dozer needs some right of os I have not set...

**Comment by thebitguru** [comment]
What version of macOS are you using?  Is it not starting?

**Comment by wupuyuan** [comment]
10.15.1, Dozer auto launch at login and working with hot keys

**Comment by thebitguru** [comment]
Sorry, I am still not sure of the issue that you are having.  Are you able to share a screenshot of what you are seeing?  Maybe that we will help explain...?

**Comment by wupuyuan** [comment]
<img width="589" alt="Snipaste_2019-11-05_09-46-34" src="https://user-images.githubusercontent.com/7089112/68172081-33829180-ffb1-11e9-96ca-6c77bd3c1db6.png">
This is my screenshot. 
Click icon in red, and show icons in blue. Then I want hide icons in blue after some seconds...

**Comment by thebitguru** [comment]
I see.  Thanks for the screenshots.  Your setup and configuration seems to be exactly what I would expect so this is likely a bug.

I do see issue #83 is reporting a possibly similar problem that was fixed in an unreleased PR #78.  Maybe that will fix the issue...?

@Mortennn any thoughts on this, and when the next version might be released?

**Comment by wupuyuan** [comment]
Wait for your new version...

**Comment by Mortennn** [comment]
I've released a prerelease with the changes [Dozer.4.1.0](https://github.com/Mortennn/Dozer/releases/tag/4.1.0).

**Comment by thebitguru** [comment]
@Mortennn for some reason the icons are not autohiding for me in this release after the 10 second delay.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/163550/68417645-66b55400-015c-11ea-9f93-9c165aad6590.png">

**Comment by thebitguru** [comment]
The autohide functionality does seem to be working for me now so I am not sure what was off last time.

@wupuyuan are you good as well?

**Comment by wupuyuan** [comment]
Well, I update to 4.10.
"Hide status bar icons at launch" worked,
"Hide status bar icons after 10s " still not working...
Wait for your next version?

**Comment by wupuyuan** [comment]
PS, I download Dozer 4.1, and it wants to update to version 4.0 ...


![Snipaste_2019-11-14_09-06-50](https://user-images.githubusercontent.com/7089112/68817926-37539980-06be-11ea-8f4e-5315ce333992.jpg)

**Comment by thebitguru** [comment]
Weird.  I am not sure about the issue.

FYI, the update issue is already being tracked in #84

**Comment by wupuyuan** [comment]
Yes, I read  issue84, but this is happened on my mac...
may be next version well ok, or I try to clear Dozer and install again..

**Comment by andyhuai** [comment]
I have the same question, Dozer version is 4.1.0(8), and my Mac is 10.13.3,  after 10s not hide icons

**Comment by Gabirel** [comment]
Same issue here. Doesn't work in Dozer version 4.1.0(8) as well. Please fix it. It's really annoying.

**Comment by zyhparis** [comment]
Love this App! But I have the same issue for 4.2.0, it just won't auto hide icons after 10 seconds.

**Comment by ryanbenoir** [comment]
Having thesame problem. Running OSX 10.15.5 not auto hiding. You can fix it by making a shortcut. Mine is  control command Z but it would be more easy if the auto hide function would work properly
